---
title: "T-tests_FISH"
author: "Marissa Wright-LaGreca"
date: "17/02/2023"
output: html_document
---
#
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

##FISH data - t tests on gene expression data (NKA/EFU)

install.packages("datarium")
install.packages("rstatix")
install.packages("ggpubr")
install.packages("tidyverse")

library("datarium")
library(tidyverse)
library(ggpubr)
library(rstatix)
library(ggResidpanel)
library(DHARMa)
library(dplyr)

setwd("~/FISH/FISH_t-test")

#load data

Data=read.table("FISH_data.txt",header=TRUE)
> View(Data)

Data <- nka_single_cell

#get mean NKA/EFU expression stats

set.seed(123)
Data %>% sample_n_by(treatment, size = 2)

Data %>%
  group_by(Seawater) %>%
  get_summary_stats(NKA.EFU, type = "mean_sd")

# Welsh t-test = assume variance between groups are not the same 

res <- t.test(nka..1. ~ development, data = Data)

#load res

res

# results - p < 0.05 (p = 2.533e-0.5) = there is significant difference between NKA/EFU expression between seawater treatment

stat.test <- Data %>%
  t_test(nka..1. ~ development) %>%
  add_significance()
stat.test

#2 way anova 
#Test normality
shapiro.test(Data$nka..1.) #does not pass
#Test homogeneity of variance (or homoscedasticity) 
leveneTest(nka..1. ~ development*treatment, data = Data) #passes

#use non-parametic ANOVA - ART test
install.packages("ARTool")
library(ARTool)

str(Data)
Data$treatment <- as.factor(Data$treatment)
Data$development <- as.factor(Data$development)

art_model <- art(nka..1. ~ development*treatment, data = Data)

anova_result <- anova(art_model)
print(anova_result)

result <- kruskal.test(nka..1. ~ treatment, data = Data_notrocs)

Data_notrocs <- filter(Data, development != "trocophore")


#Visualize results

# Create a box-plot without color and data points
bxp <- ggboxplot(
  Data_notrocs, x = "treatment", y = "nka..1.", 
  ylab = "Relative NKA Expression", xlab = "", add = "jitter"
)

#creat box plot wihtout color and no data points

bxp <- ggboxplot(
  Data, x = "Seawater", y = "NKA.EFU", 
  ylab = "Relative NKA Expression", xlab = "",)

# box plot with color

bxp <- ggboxplot(df, x = "", y = "Relative NKA Expression", fill = "Seawater", palette = c("#00AFBB","#FC4E07"))

#add p value

bxp <- ggboxplot(df, x = "", y = "Relative NKA Expression", fill = "Seawater", palette = c("#00AFBB","#FC4E07"))
stat.test <- stat.test %>% add_xy_position(x = "Seawater")
bxp + 
  stat_pvalue_manual(stat.test, label = "p.signif") +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1)))


#Customize p-value labels using glue expression 
# https://github.com/tidyverse/glue
#change bracket.nudge.y to adjust where p value text sits


bxp + stat_pvalue_manual(
  stat.test, label = "p.signif,
  vjust = -1, bracket.nudge.y = 0.1
) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1)))
  
  # add a more detailed p value and statistics
  
  stat.test <- stat.test %>% add_xy_position(x = "Seawater")
bxp + 
  stat_pvalue_manual(stat.test, tip.length = 0) +
  labs(subtitle = get_test_label(stat.test, detailed = TRUE))
